class EmotionModel:
    def __init__(self, model_name="8_cls"):
        self.models = {
            "6_cls": ["Joy", "Surprise", "Anger", "Disgust", "Fear", "Sadness"],
            "7_cls": [
                "Happiness",
                "Sadness",
                "Surprise",
                "Fear",
                "Disgust",
                "Anger",
                "Contempt",
            ],
            "8_cls": [
                "Amusement",
                "Awe",
                "Contentment",
                "Excitement",
                "Anger",
                "Disgust",
                "Fear",
                "Sadness",
            ],
            "24_cls": [
                "joy",
                "serenity",
                "ecstasy",
                "trust",
                "acceptance",
                "admiration",
                "fear",
                "apprehension",
                "terror",
                "surprise",
                "distraction",
                "amazement",
                "sadness",
                "pensiveness",
                "grief",
                "disgust",
                "boredom",
                "loathing",
                "anger",
                "annoyance",
                "rage",
                "anticipation",
                "interest",
                "vigilance",
            ],
            "26_cls": [
                "Affection",
                "Anger",
                "Annoyance",
                "Anticipation",
                "Aversion",
                "Confidence",
                "Disapproval",
                "Disconnection",
                "Disquietment",
                "Doubt/Confusion",
                "Embarrassment",
                "Engagement",
                "Esteem",
                "Excitement",
                "Fatigue",
                "Fear",
                "Happiness",
                "Pain",
                "Peace",
                "Pleasure",
                "Sadness",
                "Sensitivity",
                "Suffering",
                "Surprise",
                "Sympathy",
                "Yearning",
            ],
            "VA": ["Valence", "Arousal"],
        }
        self.model_name = model_name

    def get_labels(self):
        return self.models.get(self.model_name, [])

    def list_models(self):
        return list(self.models.keys())
